### ISSUE TITLE
Info on FASTQ example

### ISSUE THREAD

**Issue by telatin** [adriantich/DnoisE#15]
Hi there,
I noticed the FASTQ file provided in the test directory is malformed with quality as:

```
RANDOMQVALUES#####77777793864390
```

Was this done on purpose?

**Comment by adriantich** [comment]
Hi Andrea I've seen I answered you via mail and is not abailable for other users. 
''''
Hi Andrea,

The FASTQ files provided are just examples that we created manually from random fasta files. In the 4th line of each sequence is supposed to be given some quality values that in fasta files are not present. Thus we added this string to simulate the quality line. In fact both fasta and fastq files provided are just examples to test the DnoisE use not the ecological results.

We created those files manually to include some character strings that gave errors in solved bugs in the past when other users started to use DnoisE.

Please don't use our FASTQ files as real examples

Did you have any problem with your fastq files?

Adrià
''''
